### ISSUE TITLE
Extension creates shortcuts using OS key / Command instead of control

### ISSUE THREAD

**Issue by svallory** [thiagomajesk/code-flow#1]
I know that most of the time, that's what people do. But if you are trying to avoid conflicts, I think it makes more sense to use the inverse of the common for each system.

I think the best solution would be to allow the user to select a combination of modifier keys. It is easier to free all `ctrl+os_key+[something]` than to make sure nothing has been overridden.

If that is too troublesome, you could let the user pick between `ctrl` and `command`

Other than that, congrats on the great extension!

Btw, if you want to add ergonomic navigation by remapping the arrow keys to the `i j k l` / `h j k l` let me know. I created a nice modification for karabiner that I think can be configured in the extension with minor tweeks

**Comment by thiagomajesk** [comment]
Hi @svallory! 

Thanks for the suggestion… I’m not actively working on this extension anymore though. 

My main goal with this extension was providing some keyboard-centric workflow but since then I learned that doing strong chord-based shortcuts is not actually too good ergonomics.

Last I had some spare time to work in this extension I was studying new ways to make my vision come through (including some sort of modal editing) but I found myself battling to much against VSCode limitations.

In the future, If I manage to find a better solution to solve my own problems with this workflow I’ll be open to new discussions - that is, if I’m still using VSCode by then.

Cheers!

**Comment by svallory** [comment]
No worries, I did a find+replace on the installed extension code and solved the problem for me :)

If you decide to come back to this kind of endeavour (one can loose hooours messing with shortcuts), since you focus on productivity, maybe you should make an extension to configure prefixes for shortcut groups. That way you can modify many prefixes at a time. That would at least allow you to test shortcut schemas very fast.

Anyways, thanks for the work you've done! It saved me some time :)
